### ISSUE TITLE
Issue with JDBC and multiple prepared statements: ERROR: expected x prepared parameters but received y

### ISSUE THREAD

**Issue by Degola** [pipelinedb/pipelinedb#1204]
We experienced the issue that we get the error "ERROR: expected x prepared parameters but received y":
```debug
0 = {HashMap$Node@1330} "R" -> "InsertIntoStreamPrepared"
1 = {HashMap$Node@1331} "S" -> "ERROR"
2 = {HashMap$Node@1332} "C" -> "XX000"
3 = {HashMap$Node@1333} "F" -> "stream.c"
4 = {HashMap$Node@1334} "L" -> "277"
5 = {HashMap$Node@1335} "M" -> "expected 3 prepared parameters but received 4"
```

This happens with more than one prepared statement per connection and doing the insert into a stream before inserting into a normal table.

Please find below the corresponding table schemata and a junit test case.

Table schema:
```sql
CREATE STREAM events_heartbeat (
  product_id VARCHAR(24),
  unique_user_id VARCHAR(24),
  insert_date TIMESTAMPZ
);
CREATE TABLE facts__users_first_and_last_activity (
  product_id VARCHAR(24),
  unique_user_id VARCHAR(24),
  first_seen_date TIMESTAMPTZ,
  last_seen_date TIMESTAMPTZ,
  CONSTRAINT facts_users_activity_product_id_unique_user_id UNIQUE (product_id, unique_user_id)
);
```

junit test case:

```java
package com.iqu.ding.analytics.storage;

import java.sql.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Properties;

import static org.junit.Assert.*;

public class PipelineDbPrepareStatementTest {
    Connection connection;
    String productId;
    String uniqueUserId;
    String country;
    Timestamp timestamp;

    @org.junit.Before
    public void setup() throws Exception {
        String dsn = "jdbc:postgresql://10.40.0.41:5432/analytics";
        Properties connectionProperties = new Properties();
        connectionProperties.put("user", "xxx");
        connectionProperties.put("password", "xxx");

        connection = DriverManager.getConnection(dsn, connectionProperties);
        productId = "xxx";
        uniqueUserId = "xxx";
        country = "NL";

        Date date;
        Calendar cal = GregorianCalendar.getInstance();
        cal.set(2015, 0, 1);

        timestamp = new Timestamp(cal.getTime().getTime());

    }

    @org.junit.Test
    public void testUpdateInsertPrepareStatementWithStreamInsertAfter() throws Exception {
        PreparedStatement statementHeartbeat = connection.prepareStatement("INSERT INTO " +
            "events_heartbeat (product_id, unique_user_id, insert_date) " +
            "VALUES " +
            "(?, ?, ?)"
        );

        PreparedStatement statementFirstActivity = connection.prepareStatement("INSERT INTO " +
                "facts__users_first_and_last_activity " +
                "(product_id, unique_user_id, first_seen_date, last_seen_date) " +
            "VALUES " +
                "(?, ?, ?, ?)"
        );

        PreparedStatement deleteActivity = connection.prepareStatement(
                "DELETE FROM facts__users_first_and_last_activity WHERE unique_user_id=?"
        );

    	// this works
        statementFirstActivity.setString(1, productId);
        statementFirstActivity.setString(2, uniqueUserId);
        statementFirstActivity.setTimestamp(3, timestamp);
        statementFirstActivity.setTimestamp(4, timestamp);
        statementFirstActivity.executeUpdate();

        statementHeartbeat.setString(1, productId);
        statementHeartbeat.setString(2, uniqueUserId);
        statementHeartbeat.setTimestamp(3, timestamp);
        statementHeartbeat.executeUpdate();

        deleteActivity.setString(1, uniqueUserId);
        deleteActivity.execute();

    }
    @org.junit.Test
    public void testUpdateInsertPrepareStatementWithStreamInsertBefore() throws Exception {
        PreparedStatement statementHeartbeat = connection.prepareStatement("INSERT INTO " +
            "events_heartbeat (product_id, unique_user_id, insert_date) " +
            "VALUES " +
            "(?, ?, ?)"
        );

        PreparedStatement statementFirstActivity = connection.prepareStatement("INSERT INTO " +
                "facts__users_first_and_last_activity " +
                "(product_id, unique_user_id, first_seen_date, last_seen_date) " +
            "VALUES " +
                "(?, ?, ?, ?)"
        );

        PreparedStatement deleteActivity = connection.prepareStatement(
                "DELETE FROM facts__users_first_and_last_activity WHERE unique_user_id=?"
        );

        statementHeartbeat.setString(1, productId);
        statementHeartbeat.setString(2, uniqueUserId);
        statementHeartbeat.setTimestamp(3, timestamp);
        statementHeartbeat.executeUpdate();

    	// this doesn't work
        statementFirstActivity.setString(1, productId);
        statementFirstActivity.setString(2, uniqueUserId);
        statementFirstActivity.setTimestamp(3, timestamp);
        statementFirstActivity.setTimestamp(4, timestamp);
        statementFirstActivity.executeUpdate();

        deleteActivity.setString(1, uniqueUserId);
        deleteActivity.execute();

    }
}
```

We're using PipelineDB 0.8.1 and Java 1.8 with the following maven dependency for the JDBC Postgresql driver :
```xml
 <dependency>
  <groupId>org.postgresql</groupId>
  <artifactId>postgresql</artifactId>
  <version>9.4-1202-jdbc41</version>
</dependency>
```

**Comment by derekjn** [comment]
Thanks for the report @Degola , we're looking into it.

**Comment by EliSnow** [comment]
I have encountered this bug within Node.js as well.

**Comment by derekjn** [comment]
@EliSnow @Degola this has been fixed and the [https://www.pipelinedb.com/download](nightly build) was just updated. Thanks!

**Comment by EliSnow** [comment]
@derekjn, I just tried out the latest nightly and I'm still experiencing this in Node. Since this issue was specific to JDBC, shall I create a new issue?

**Comment by derekjn** [comment]
Hi @EliSnow , can you show us the output of `SELECT pipeline_version()`? The nightly build links are lower down on the page and it's possible you don't have the latest version. Thanks!

**Comment by EliSnow** [comment]
```
PipelineDB 0.8.1 at revision 8b0b1d48d04ec3dac572ef613646d803795e259b on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit
```

**Comment by derekjn** [comment]
Ok that looks good. I'll reopen this issue and it would be helpful if you could share a repro case with Node.

**Comment by EliSnow** [comment]
Here's a pared down js file which replicates the issue (let me know if you need more than this):
```js
"use strict";
let pg = require("pg");

let connectString = 'postgres://db_user:password@192.168.99.100/stats';
let delimiter = '\r\n';

pg.connect(connectString, (err, client, done) => {
  if (err) {
    console.error(err);
    return;
  }
  let data = '{"foo":"bar"}\r\n{"baz":"bux"}\r\n';
  client.query(
    {
      name: "junk",
      text: `INSERT INTO tsd_stream (js) SELECT unnest(string_to_array(left($1, -${delimiter.length}), $2)::jsonb[])`,
      values: [data, delimiter]
    },
    (err, response) => {
      done();
      if (err) {
        console.error(err);
        console.log(data);
      }
    });
});
```
This is using the npm library [ps](https://www.npmjs.com/package/pg) so a `npm install ps` will resolve that dependency. The stream `tsd_stream` has a single jsonb column `js`.

I'm actually experiencing two issues:
1) in the version above the error returned is `error: expected 1 prepared parameters but received 2`. 
2) my original version did not have `delimiter` as a parameter rather it was concatenated directly into the query string (since it is hardcoded into the server code, it is "safe"). However that resulted in bizarre parsing errors on each of the continuous views feeding off of `tsd_stream`. To demonstrate this problem if you have one or more continuous views using `tsd_stream` and you replace the above query object with:
```js
{
    name: "junk",
    text: `INSERT INTO tsd_stream (js) SELECT unnest(string_to_array(left($1, -${delimiter.length}), '${delimiter}')::jsonb[])`,
    values: [data]
}
```
In the database logs you will a json parsing error on every continuous view feeding off of `tsd_stream`. 
```
ERROR:  invalid input syntax for type json
DETAIL:  Expected end of input, but found "{".
```
If you change the `INSERT` into a `SELECT`, you will see the json is parsed correctly:
```js
{
    name: "junk",
    text: `SELECT unnest(string_to_array(left($1, -${delimiter.length}), '${delimiter}')::jsonb[])`,
    values: [data]
}
```
Which seems to indicate the error is happening when PipelineDB is parsing the query.

**Comment by derekjn** [comment]
Thanks @EliSnow , I'm moving this over to #1213.
